"""Pre-commit hook entry point for ``detect-secrets-hook``."""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import textwrap
from typing import List, Optional

import detect_secrets_rs as rs


# ---------------------------------------------------------------------------
# Exit codes
# ---------------------------------------------------------------------------

EXIT_NO_SECRETS = 0
EXIT_SECRETS_FOUND = 1
EXIT_BASELINE_UPDATED = 3


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="detect-secrets-hook",
        description="Pre-commit hook for detect-secrets-rs.",
    )
    parser.add_argument("--version", action="version", version=rs.version())
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument(
        "filenames",
        nargs="*",
        help="Filenames to check.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="output_json",
        help="Print output as JSON.",
    )
    parser.add_argument(
        "--baseline",
        metavar="FILENAME",
        default=None,
        help="Baseline file generated by ``detect-secrets scan``.",
    )

    # Plugin options
    group = parser.add_argument_group(title="plugin options")
    group.add_argument(
        "--list-all-plugins",
        action="store_true",
        help="List all plugins that will be used.",
    )
    group.add_argument(
        "-p", "--plugin",
        nargs=1,
        action="append",
        help="Path to custom secret detector plugin.",
    )
    group.add_argument(
        "--base64-limit",
        type=float,
        default=None,
        help="Entropy limit for Base64 strings (0.0–8.0).",
    )
    group.add_argument(
        "--hex-limit",
        type=float,
        default=None,
        help="Entropy limit for Hex strings (0.0–8.0).",
    )
    group.add_argument(
        "--disable-plugin",
        nargs=1,
        action="append",
        help="Plugin class name to disable.",
    )

    # Filter options
    fgroup = parser.add_argument_group(title="filter options")
    verify = fgroup.add_mutually_exclusive_group()
    verify.add_argument(
        "-n", "--no-verify",
        action="store_true",
        help="Disable additional verification via network calls.",
    )
    verify.add_argument(
        "--only-verified",
        action="store_true",
        help="Only flag secrets that can be verified.",
    )
    fgroup.add_argument("--exclude-lines", type=str, action="append")
    fgroup.add_argument("--exclude-files", type=str, action="append")
    fgroup.add_argument("--exclude-secrets", type=str, action="append")
    fgroup.add_argument("--word-list", dest="word_list_file", default=None)
    fgroup.add_argument("-f", "--filter", nargs=1, action="append")
    fgroup.add_argument("--disable-filter", nargs=1, action="append")

    return parser


# ---------------------------------------------------------------------------
# Settings initialisation
# ---------------------------------------------------------------------------

def _initialize_settings(args: argparse.Namespace) -> Optional[dict]:
    """Populate global settings from baseline / CLI flags.

    Returns the loaded baseline dict (or None).
    """
    baseline_data = None

    if args.baseline and os.path.isfile(args.baseline):
        baseline_data = rs.baseline_load_from_file(args.baseline)
        rs.configure_settings_from_baseline(baseline_data, args.baseline)
    else:
        rs.global_initialize_all_plugins()

    # Plugin overrides
    if args.disable_plugin:
        names = [n for item in args.disable_plugin for n in item]
        rs.global_disable_plugins(names)

    if args.base64_limit is not None:
        rs.global_set_plugin_limit("Base64HighEntropyString", "limit", args.base64_limit)

    if args.hex_limit is not None:
        rs.global_set_plugin_limit("HexHighEntropyString", "limit", args.hex_limit)

    # Filter overrides
    if args.exclude_lines:
        rs.global_set_filter(
            "detect_secrets.filters.regex.should_exclude_line",
            {"pattern": args.exclude_lines},
        )

    if args.exclude_files:
        rs.global_set_filter(
            "detect_secrets.filters.regex.should_exclude_file",
            {"pattern": args.exclude_files},
        )

    if args.exclude_secrets:
        rs.global_set_filter(
            "detect_secrets.filters.regex.should_exclude_secret",
            {"pattern": args.exclude_secrets},
        )

    if args.word_list_file:
        rs.global_set_filter(
            "detect_secrets.filters.wordlist.should_exclude_secret",
            {"file_name": args.word_list_file, "min_length": 3},
        )

    if args.no_verify:
        rs.global_disable_filters([
            "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
        ])

    if args.disable_filter:
        paths = [p for item in args.disable_filter for p in item]
        rs.global_disable_filters(paths)

    if args.filter:
        paths = [p for item in args.filter for p in item]
        for path in paths:
            rs.global_set_filter(path, {})

    return baseline_data


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _get_changed_but_unstaged_files() -> set:
    """Return set of files that are changed but not staged in git."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only"],
            capture_output=True, text=True, check=False,
        )
        return set(result.stdout.strip().splitlines()) if result.returncode == 0 else set()
    except FileNotFoundError:
        return set()


def _raise_if_baseline_unstaged(filename: str) -> None:
    """Abort if the baseline file has unstaged changes."""
    if filename in _get_changed_but_unstaged_files():
        print(
            f"Your baseline file ({filename}) is unstaged.\n"
            f"`git add {filename}` to fix this.",
            file=sys.stderr,
        )
        raise ValueError


def _should_update_baseline(
    baseline_secrets: rs.SecretsCollection,
    scanned_results: rs.SecretsCollection,
    filelist: list,
    baseline_version: str,
) -> bool:
    """Return True if the baseline needs to be updated."""
    original = rs.SecretsCollection.load_from_baseline(
        {"results": baseline_secrets.json()}
    )
    baseline_secrets.trim(scanned_results=scanned_results, filelist=filelist)

    if baseline_version != rs.baseline_version():
        return True

    if not baseline_secrets.exactly_equals(original):
        return True

    return False


def _pretty_print_diagnostics(secrets: rs.SecretsCollection, width: int = 80) -> None:
    """Human-readable error output for found secrets."""
    header = "ERROR: Potential secrets about to be committed to git repo!"
    print(textwrap.fill(header, width=width))
    print()

    for filename in secrets.files:
        for secret in secrets[filename]:
            print(f"{secret}")

    print(f"\nTotal secrets detected: {len(secrets)}")

    print("Possible mitigations:")
    security_team = os.environ.get("DETECT_SECRETS_SECURITY_TEAM", "in #security")
    suggestions = [
        f"For information about putting your secrets in a safer place, "
        f"please ask {security_team}",
        "Mark false positives with an inline "
        "`pragma: allowlist secret` comment",
    ]
    wrapper = textwrap.TextWrapper(
        initial_indent="  - ",
        subsequent_indent="    ",
        width=width,
    )
    for suggestion in suggestions:
        print(wrapper.fill(suggestion))

    print()
    print(
        textwrap.fill(
            "If a secret has already been committed, visit "
            "https://help.github.com/articles/removing-sensitive-data-from-a-repository",
            width=width,
        )
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    parser = _build_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        return exc.code if isinstance(exc.code, int) else 1

    rs.cache_bust()

    if args.baseline:
        try:
            _raise_if_baseline_unstaged(args.baseline)
        except ValueError:
            return EXIT_SECRETS_FOUND

    baseline_data = _initialize_settings(args)

    # Scan all specified files
    secrets = rs.SecretsCollection()
    for filename in args.filenames:
        secrets.scan_file(filename)

    # Compare with baseline
    new_secrets = secrets
    if args.baseline and baseline_data is not None:
        baseline_secrets = rs.baseline_load(baseline_data, args.baseline)
        new_secrets = secrets - baseline_secrets

    if new_secrets:
        if args.output_json:
            output = rs.baseline_format_for_output(new_secrets, False)
            print(json.dumps(output, indent=2))
        else:
            _pretty_print_diagnostics(new_secrets)
        return EXIT_SECRETS_FOUND

    if not args.baseline or baseline_data is None:
        return EXIT_NO_SECRETS

    # Check if baseline needs updating
    baseline_secrets = rs.baseline_load(baseline_data, args.baseline)
    baseline_version = baseline_data.get("version", "")

    is_modified = _should_update_baseline(
        baseline_secrets,
        scanned_results=secrets,
        filelist=args.filenames,
        baseline_version=baseline_version,
    )

    if is_modified:
        if baseline_version != rs.baseline_version():
            old_baseline = rs.baseline_load_from_file(args.baseline)
            old_baseline["results"] = baseline_secrets.json()
            baseline_data = rs.baseline_upgrade(old_baseline)
            baseline_secrets = rs.baseline_load(baseline_data, args.baseline)

        output = rs.baseline_format_for_output(baseline_secrets, False)
        rs.baseline_save_to_file(output, args.baseline)
        print(
            "The baseline file was updated.\n"
            "Probably to keep line numbers of secrets up-to-date.\n"
            f"Please `git add {args.baseline}`, thank you.\n"
        )
        return EXIT_BASELINE_UPDATED

    return EXIT_NO_SECRETS


if __name__ == "__main__":
    sys.exit(main())
